"""
FastAPI Dependency Injection: RAG Pipeline
 
Using dependency injection for the RAG pipeline means:
    1. The pipeline is initialized once at startup (not per request)
    2. Tests can inject a mock pipeline without changing route code
    3. Pipeline configuration is centralized
 
Design decision: singleton pipeline via lru_cache
    The RAG pipeline is expensive to initialize (embedding model,
    FAISS index loading). We create it once and reuse across requests.
    lru_cache on the dependency function achieves this cleanly.
"""
 
from functools import lru_cache
from typing import Optional
import os
 
 
class MockPipeline:
    """
    Mock RAG pipeline for development and testing.
 
    Returns realistic-looking responses without requiring
    actual documents, embeddings, or LLM API keys.
    """
 
    class MockVectorStore:
        size = 10
 
    vector_store = MockVectorStore()
 
    def query(self, question: str, k: int = 5, metadata_filter=None):
        """Return a mock response."""
        from dataclasses import dataclass
 
        @dataclass
        class MockResult:
            answer: str
            model: str
            prompt_tokens: int
            completion_tokens: int
            context_chunks: list
 
        return MockResult(
            answer=(
                f"This is a mock answer for: '{question}'. "
                f"In production, this would be generated by the RAG pipeline "
                f"using retrieved context from your knowledge base."
            ),
            model="mock-gpt-4",
            prompt_tokens=150,
            completion_tokens=80,
            context_chunks=[]
        )
 
 
@lru_cache(maxsize=1)
def _get_pipeline_instance():
    """
    Create and cache the RAG pipeline instance.
 
    Called once at first request. Subsequent requests use
    the cached instance, no re-initialization overhead.
 
    In production:
        - Load vector store from VECTOR_STORE_PATH
        - Initialize with Azure OpenAI credentials
        - Apply production chunking + retrieval config
    """
    vector_store_path = os.getenv("VECTOR_STORE_PATH", "")
    use_mock = not vector_store_path or not os.path.exists(vector_store_path)
 
    if use_mock:
        print("[Pipeline] No vector store found, using mock pipeline")
        print("[Pipeline] Set VECTOR_STORE_PATH in .env to use real pipeline")
        return MockPipeline()
 
    # Production pipeline initialization
    # Uncomment and configure for production use:
    #
    # from src.pipeline import RAGPipeline, PipelineConfig
    # from src.ingestion.chunker import SentenceWindowChunker
    #
    # pipeline = RAGPipeline(
    #     chunker=SentenceWindowChunker(window_size=2),
    #     config=PipelineConfig(llm_model=os.getenv("AZURE_OPENAI_DEPLOYMENT"))
    # )
    # pipeline.load(vector_store_path)
    # return pipeline
 
    return MockPipeline()
 
 
def get_pipeline():
    """
    FastAPI dependency — returns the pipeline instance.
 
    Used via Depends(get_pipeline) in route handlers.
    Override in tests by using app.dependency_overrides.
    """
    return _get_pipeline_instance()